version: "3.3"
services:
  fivefilters-full-text-rss:
    container_name: full-text-rss
    ports:
      - "50000:80"
    restart: always
    image: "heussd/fivefilters-full-text-rss:latest"
  linuxserver:
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "80:80"
    volumes:
      - "/path/to/data:/config"
    restart: unless-stopped
    image: "lscr.io/linuxserver/freshrss:latest"
